bracketSpacing: true
jsxBracketSameLine: false
printWidth: 80
semi: true
singleQuote: true
tabWidth: 4
trailingComma: all
useTabs: false
overrides:
  - files: ['*.php']
    options:
      braceStyle: psr-2
      parser: php
      trailingCommaPHP: php5
